name: humdam_soulsync
description: AI companion app Humdam (India) / SoulSync (global)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  firebase_messaging: ^15.1.0
  http: ^1.2.0
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.3
  table_calendar: ^3.1.0
  pie_chart: ^5.3.2
  razorpay_flutter: ^1.3.7
  image_picker: ^1.0.7
  device_frame: ^1.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  uuid: ^4.2.2
  url_launcher: ^6.3.0
  google_sign_in: ^6.2.1
  js: ^0.7.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/


